### ISSUE TITLE
License for this project and the items in it?

### ISSUE THREAD

**Issue by avamk** [stared/science-based-games-list#14]
Hello,

Great list!

Can you please add a LICENSE file for this repository, e.g. CC BY-SA 4.0?

Also, there should be a license section for each game as well such as "proprietary", GPL, MIT, etc. And to be clear, free of charge games should be labelled "free of charge" or "gratis" instead of just "free". Thanks!

**Comment by stared** [comment]
With license - for such projects my personal approach is [WTFPL](http://www.wtfpl.net/), but to make it more well-behaved I am happy to go with [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (or at most CC BY). Looks good?

Games - well, this section with "free" is just here to tell if you can play it without paying anyone ("free as in beer").
For a more detailed list with licenses, repos, etc - it's worth it (do you want to fill it by yourself? :)) but then, I guess, in a YAML file.

**Comment by avamk** [comment]
Thanks for your quick reply!! Between CC0 and CC BY, CC BY sounds best to me but that's my personal opinion. :)

I'll be happy to add licensing info for each game, but I'm not good with YAML so might start with the existing list. I'll work on it with my other account and send you a pull request.

**Comment by stared** [comment]
If you can add, it would be wonderful! 

In this just go I suggest adding a bullet point with:

`* open source (GPL), [source code](http://)`

**Comment by penyuan** [comment]
OK, I just submitted a pull request. In addition to license, I added price and compatible platforms when possible. Oh, and I added the Code Master board game.

**Comment by stared** [comment]
Great! 
Continued in pull request. #27
