### ISSUE TITLE
Programming: "Infinifactory"

### ISSUE THREAD

**Issue by JayAndCatchFire** [stared/science-based-games-list#23]
The list already has a ton of great games from Zachtronics, but it's missing one of my favorites: [Infinifactory](http://www.zachtronics.com/infinifactory/)!

**Comment by stared** [comment]
So, open a Pull Request. :)

**Comment by JayAndCatchFire** [comment]
https://github.com/stared/science-based-games-list/pull/24

**Comment by stared** [comment]
Merged, thx!
