### ISSUE TITLE
Dragon box games (add to Math)

### ISSUE THREAD

**Issue by secretGeek** [stared/science-based-games-list#53]
(Sorry this is in the form of an issue not a PR... bit strapped for time)

Dragonbox make an amazing, mind-blowing game that teaches kids to manipulate and solve equations. https://dragonbox.com/products/algebra-5#5+ 

They also have a geometry game that teaches you Euclid's Elements  https://dragonbox.com/products/elements

**Comment by stared** [comment]
Well, PR is an only way to post it. :)

In any case - this game has vibe (or at least marketing/homepage) "for classroom only". Haven't played that, so not sure if it is the case. @secretGeek, what your opinion on that?

**Comment by secretGeek** [comment]
Thanks for the reply. I understand the lists need to avoid “for classroom only” (it’s a great idea for separating the ones you want) but these games are definitely more for personal enjoyment. 

The kids don’t realise until years later that they’ve mastered a skill they’ll use in the classroom. It’s extremely clever.

I’ll close this issue and on my personal todo list I’ll ask myself to post a PR with these ones. (Sometimes future-self doesn’t do the things present-self asks of him though 🤷‍♂️)
