### ISSUE TITLE
Suggestion to add awesome_bot

### ISSUE THREAD

**Issue by htadashi** [stared/science-based-games-list#57]
Hi, thanks for maintaining this awesome list!  
I am writing this issue to suggest [awesome_bot](https://github.com/dkhamsing/awesome_bot) to automatically check for broken links.

**Comment by stared** [comment]
Thanks @htadashi, it is a good idea.

Recently, I started using GitHub Action in another project (https://github.com/Quantum-Game/qg-encyclopedia/runs/573827083), although with a different tool (https://github.com/gaurav-nelson/github-action-markdown-link-check).

Do you also a version for GH Actions?

**Comment by htadashi** [comment]
Hi @stared , I am not contributor of awesome_bot, just thought it would be interesting to share this tool here :) 
Unfortunately, I do not know if there is a version for GH Actions...

**Comment by stared** [comment]
Added a checker (albeit a different one).
