### ISSUE TITLE
Games teaching digital logical design

### ISSUE THREAD

**Issue by htadashi** [stared/science-based-games-list#63]
Could I add these two games on digital logical design?

#### nandgame

* [http://nandgame.com/](http://nandgame.com/)
* digital logic and computer design
* puzzle
* build a processor from start
* web-based (free of charge)

#### Digital Logic Design (The Game)

* [http://asteriskman7.github.io/dldtg/](http://asteriskman7.github.io/dldtg/)
* digital logic design
* increment game
* web-based (free of charge)
* GPLv3 License: [https://github.com/asteriskman7/dldtg]

**Comment by stared** [comment]
@htadashi Nandgame is awesome! Please add it as a pull request, I will merge it happily! :)

**Comment by htadashi** [comment]
@stared Here you go :)

**Comment by stared** [comment]
Thanks, merged! 

The other looks nice as well, feel free to PR it as well.
